# Generated by Django 4.0.2 on 2022-03-01 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prdocutname',
            new_name='productname',
        ),
    ]
